consul:  
  image: scottyc/consul
  hostname: consul-slave
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "53:53/udp"
  command: -server --advertise <$IP> --join <$JOIN_IP>
 # Replace <$IP> with host ip and <$JOIN_IP> with the consul master ip address