consul:  
  image: scottyc/consul
  hostname: consul-master
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "53:53/udp"
  command: -server --advertise <$IP> -bootstrap-expect 3

  # Replace <$IP> with real ip address 